name: Build

on:
  push:
    branches:
      - main
      - hml
      - dev

jobs:
  build:
    name: Build Stage
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: List Modified YAML Files
        id: list-yaml-files
        run: echo "::set-output name=modified_yaml_files::$(git diff --name-only -- '*.yaml' '*.yml' ${{ github.event.before }} ${{ github.sha }})"

      - name: Install yamllint
        run: |
          pip install --upgrade pip
          pip install yamllint

      - name: Install yq
        run: sudo apt-get install yq

      - name: Test and Lint Modified YAML Files
        run: |
          modified_yaml_files="${{ steps.list-yaml-files.outputs.modified_yaml_files }}"
          for file in $modified_yaml_files; do
            echo "Testing and linting YAML file: $file"
            yamllint $file
            yq eval '.' $file > /dev/null
          done

      - name: setup cli
        run: |
          mkdir -p build-artifact
          cd build-artifact
          wget -O ssd https://github.com/thiagoyeds/pipeline-apiops-template/raw/dev/ssd
          chmod +x ssd
          ./ssd --help

      - name: save build artifact
        uses: actions/upload-artifact@master
        with:
          name: build-artifact
          path: build-artifact
  deploy:
    name: Deploy Stage
    needs: build
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: download build artifact
        uses: actions/download-artifact@master
        with:
          name: build-artifact
          path: build-artifact

      - name: run ssd --help
        run: | 
          chmod +x build-artifact/ssd
          ./build-artifact/ssd --help

      - name: load env vars
        run: |
          touch file.xml
          echo "{\"default\":{\"output\": \"yaml\",\"token\": \"${{ secrets.SENSEDIA_CLI_TOKEN }}\",\"url\": \"${{ secrets.SENSEDIA_CLI_MANAGER_URL }}\"}}" > config.json
          cat config.json